import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { CommandContextProvider } from './ContextApi/commandContext'
import { ApiDataProvider } from './ContextApi/apiDataContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html data-theme='myTheme' lang="en">
      <body  className={inter.className}>
      <CommandContextProvider>
        <ApiDataProvider>
        {children}
        </ApiDataProvider>
      </CommandContextProvider>
        </body>
    </html>
  )
}
